"""
SlothOps Engine — GitHub Automation
Creates branches, commits fixed files, and opens Draft Pull Requests
on the target repository using PyGithub.
"""

from __future__ import annotations

import logging
import re
from typing import Optional

from github import Github, GithubIntegration, GithubException

from models import IssueRecord, LLMFixResponse

logger = logging.getLogger("slothops.github_automation")


def _slugify_path(file_path: str) -> str:
    """Turn a file path into a URL-safe slug for branch naming."""
    slug = re.sub(r"[^a-zA-Z0-9]", "-", file_path)
    slug = re.sub(r"-+", "-", slug).strip("-").lower()
    return slug[:50]  # keep branch names reasonable


def _build_pr_body(issue: IssueRecord, fix: LLMFixResponse) -> str:
    """Build the Markdown PR body per AI_CONTEXT.md spec."""
    # Confidence badge
    badge_emoji = {"high": "🟢", "medium": "🟡", "low": "🔴"}.get(
        fix.confidence, "⚪"
    )

    # Per-file explanations
    file_explanations = ""
    for fc in fix.files_changed:
        file_explanations += f"\n### `{fc.path}`\n{fc.explanation}\n"
        
    test_explanations = ""
    if hasattr(fix, 'generated_tests') and fix.generated_tests:
        test_explanations = "\n### Generated Tests\n"
        for tc in fix.generated_tests:
            test_explanations += f"\n- `{tc.path}`: {tc.explanation}\n"

    body = f"""## 🦥 SlothOps Auto-Fix

### Root Cause
{fix.root_cause}

### Confidence: {badge_emoji} {fix.confidence.upper()}

### Error Metadata

| Field | Value |
|-------|-------|
| Type | `{issue.error_type}` |
| Message | `{issue.error_message}` |
| File | `{issue.file_path}` |
| Function | `{issue.function_name}` |
| Line | `{issue.line_number}` |
| Occurrences | {issue.occurrence_count} |

### Changes
{file_explanations}
{test_explanations}

---

> ⚠️ **This PR was auto-generated by SlothOps.** Please review carefully before merging.
> The fix was generated by GPT-4o based on production error data.
"""
    return body


def create_fix_pr(
    issue: IssueRecord,
    fix: LLMFixResponse,
    repo,
) -> str:
    """
    Create a branch, commit the fixed files, and open a Draft PR.

    Returns the PR URL string.

    Raises:
        RuntimeError: If GitHub operations fail.
    """

    # ── Branch name ──────────────────────────────────────────────────
    slug = _slugify_path(issue.file_path or "unknown")
    short_id = issue.id[:8]
    branch_name = f"slothops/fix-{slug}-{short_id}"

    # ── Get base branch SHA ──────────────────────────────────────────
    try:
        base_ref = repo.get_branch("main")
        base_sha = base_ref.commit.sha
    except GithubException:
        raise RuntimeError("Could not access 'main' branch on target repo")

    # ── Create branch ────────────────────────────────────────────────
    try:
        repo.create_git_ref(ref=f"refs/heads/{branch_name}", sha=base_sha)
        logger.info("Created branch: %s", branch_name)
    except GithubException as exc:
        if exc.status == 422:
            # Branch may already exist (e.g. retrigger) — continue
            logger.warning("Branch already exists: %s", branch_name)
        else:
            raise RuntimeError(f"Failed to create branch: {exc}")

    # ── Commit each changed file and generated tests ────────────────
    all_changes = fix.files_changed + fix.generated_tests
    for fc in all_changes:
        try:
            # Must fetch current file to get its SHA for update
            existing = repo.get_contents(fc.path, ref=branch_name)
            if isinstance(existing, list):
                logger.warning("Path is a directory, skipping: %s", fc.path)
                continue
            repo.update_file(
                path=fc.path,
                message=f"fix: {fc.explanation[:72]}",
                content=fc.fixed_content,
                sha=existing.sha,
                branch=branch_name,
            )
            logger.info("Updated file: %s", fc.path)
        except GithubException as exc:
            if exc.status == 404:
                # File doesn't exist yet — create it
                repo.create_file(
                    path=fc.path,
                    message=f"fix: {fc.explanation[:72]}",
                    content=fc.fixed_content,
                    branch=branch_name,
                )
                logger.info("Created new file: %s", fc.path)
            else:
                raise RuntimeError(f"Failed to commit {fc.path}: {exc}")

    # ── Open Draft PR ────────────────────────────────────────────────
    pr_body = fix.pr_body or _build_pr_body(issue, fix)

    try:
        pr = repo.create_pull(
            title=fix.pr_title,
            body=pr_body,
            head=branch_name,
            base="main",
            draft=True,
        )
        logger.info("Opened Draft PR #%d: %s", pr.number, pr.html_url)
    except GithubException as exc:
        raise RuntimeError(f"Failed to create PR: {exc}")

    # ── Add label for medium confidence ──────────────────────────────
    if fix.confidence == "medium":
        try:
            pr.add_to_labels("needs-careful-review")
        except GithubException:
            logger.warning("Could not add 'needs-careful-review' label (may not exist)")

    return pr.html_url


def post_style_review_comments(pr_url: str, comments: list[dict], repo) -> None:
    """
    Post developer.json style suggestions as a single PR comment.
    Each comment dict has {file, line_hint, comment}.
    """
    body_lines = ["## 🎨 SlothOps Style Review\n"]
    body_lines.append("The following suggestions are based on your `developer.json` preferences.\n")
    body_lines.append("These are style recommendations only — no code was changed.\n")

    if not comments:
        body_lines.append("> ✅ **All clear!** No style violations found in the proposed changes.")
    else:
        for c in comments:
            file_ref = c.get("file", "unknown")
        line_hint = c.get("line_hint", "")
        suggestion = c.get("comment", "")
        body_lines.append(f"- **`{file_ref}`** ({line_hint}): {suggestion}")

    body = "\n".join(body_lines)

    # Extract PR number from URL
    try:
        pr_number = int(pr_url.rstrip("/").split("/")[-1])
        pr = repo.get_pull(pr_number)
        pr.create_issue_comment(body)
        logger.info("Posted %d style review comment(s) on PR #%d", len(comments), pr_number)
    except Exception as exc:
        logger.error("Failed to post style review comments: %s", exc)

def post_general_pr_comment(pr_url: str, comment_body: str, repo) -> None:
    """Post an overarching markdown comment on a PR."""
    if not comment_body:
        return
    try:
        pr_number = int(pr_url.rstrip("/").split("/")[-1])
        pr = repo.get_pull(pr_number)
        pr.create_issue_comment(comment_body)
        logger.info("Posted general code review comment on PR #%d", pr_number)
    except Exception as exc:
        logger.error("Failed to post general PR comment: %s", exc)

async def handle_human_pr_review(
    payload: dict,
    workspace_id: str,
    gemini_api_key: str,
    github_app_id: int,
    github_app_private_key: str,
    db_path: str
):
    """
    Handle a manually raised PR: fetch the PR files, run style and architecture
    reviews, and post the results back to the PR.
    """
    import database as db
    from style_reviewer import review_against_preferences
    from code_reviewer import review_pr_code
    
    # 1. Setup GitHub Client
    installation_id = payload.get("installation", {}).get("id")
    if not installation_id:
        return
        
    try:
        integration = GithubIntegration(github_app_id, github_app_private_key)
        access_token = integration.get_access_token(installation_id).token
        gh = Github(access_token)
        repo_name = payload["repository"]["full_name"]
        repo = gh.get_repo(repo_name)
    except Exception as e:
        logger.error("Failed to auth GitHub App for PR review: %s", e)
        return
        
    pr_number = payload["pull_request"]["number"]
    pr_url = payload["pull_request"]["html_url"]
    
    try:
        pr = repo.get_pull(pr_number)
        gh_files = pr.get_files()
    except Exception as e:
        logger.error("Failed to fetch PR #%d files: %s", pr_number, e)
        return
        
    # 2. Extract changed files & content
    changed_files = []
    for f in gh_files:
        if f.status == "removed":
            continue
        try:
            content_file = repo.get_contents(f.filename, ref=pr.head.sha)
            if not isinstance(content_file, list):
                changed_files.append({
                    "path": f.filename,
                    "content": content_file.decoded_content.decode("utf-8", errors="replace")
                })
        except Exception:
            pass # Binary files or fetch error
            
    if not changed_files:
        return
        
    # 3. Style Review
    try:
        dev_config = await db.get_developer_config(workspace_id, db_path)
        if dev_config:
            logger.info("🎨 Running Style Review for Human PR #%s...", pr_number)
            style_comments = await review_against_preferences(changed_files, dev_config, gemini_api_key)
            post_style_review_comments(pr_url, style_comments, repo)
    except Exception as e:
        logger.warning("Style review failed for Human PR: %s", e)
        
    # 4. Architecture / Logic Review
    try:
        logger.info("🧠 Running Architecture Review for Human PR #%s...", pr_number)
        try:
            ai_context_file = repo.get_contents("AI_CONTEXT.md")
            context_str = ai_context_file.decoded_content.decode("utf-8")
        except Exception:
            context_str = ""
            
        code_review_md = await review_pr_code(
            changed_files=changed_files,
            codebase_context=context_str,
            gemini_api_key=gemini_api_key,
        )
        post_general_pr_comment(pr_url, code_review_md, repo)
    except Exception as e:
        logger.warning("Code review failed for Human PR: %s", e)
